apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    workflows.argoproj.io/description: |
      This is an example of the ways array expressions can be used.
  generateName: array-
  labels:
    workflows.argoproj.io/archive-strategy: 'false'
spec:
  arguments:
    parameters:
      - name: workflow-array-param
        value: '[3,1,2,1]'
      - name: workflow-nested-param
        value: '[[1,2],[3,4]]'
      - name: workflow-array2-param
        value: '[5,6]'
  entrypoint: entrypoint
  templates:
    - inputs:
        parameters:
          - name: first-param
          - name: last-param
          - name: flatten-param
          - name: reverse-param
          - name: sort-param
          - name: uniq-param
          - name: join-param
          - name: concat-param
          - name: mean-param
          - name: median-param
          - name: take-param
          - name: all-param
          - name: any-param
          - name: one-param
          - name: none-param
          - name: map-param
          - name: filter-param
          - name: find-param
          - name: find-index-param
          - name: find-last-param
          - name: find-last-index-param
          - name: group-by-param
          - name: count-param
          - name: reduce-param
          - name: sum-param
          - name: sort-by-param
      name: array
      script:
        command:
          - '/bin/sh'
          - '-e'
        image: busybox
        source:  >
          echo "first: {{inputs.parameters.first-param}}"
                               echo "last: {{inputs.parameters.last-param}}"
                               echo "flatten: {{inputs.parameters.flatten-param}}"
                               echo "reverse: {{inputs.parameters.reverse-param}}"
                               echo "sort: {{inputs.parameters.sort-param}}"
                               echo "uniq: {{inputs.parameters.uniq-param}}"
                               echo "join: {{inputs.parameters.join-param}}"
                               echo "concat: {{inputs.parameters.concat-param}}"
                               echo "mean: {{inputs.parameters.mean-param}}"
                               echo "median: {{inputs.parameters.median-param}}"
                               echo "take: {{inputs.parameters.take-param}}"
                               echo "all: {{inputs.parameters.all-param}}"
                               echo "any: {{inputs.parameters.any-param}}"
                               echo "one: {{inputs.parameters.one-param}}"
                               echo "none: {{inputs.parameters.none-param}}"
                               echo "map: {{inputs.parameters.map-param}}"
                               echo "filter: {{inputs.parameters.filter-param}}"
                               echo "find: {{inputs.parameters.find-param}}"
                               echo "findIndex: {{inputs.parameters.find-index-param}}"
                               echo "findLast: {{inputs.parameters.find-last-param}}"
                               echo "findLastIndex: {{inputs.parameters.find-last-index-param}}"
                               echo "groupBy: {{inputs.parameters.group-by-param}}"
                               echo "count: {{inputs.parameters.count-param}}"
                               echo "reduce: {{inputs.parameters.reduce-param}}"
                               echo "sum: {{inputs.parameters.sum-param}}"
                               echo "sortBy: {{inputs.parameters.sort-by-param}}"
    - dag:
        tasks:
          - arguments:
              parameters:
                - name: first-param
                  value: "{{=first(fromJSON(workflow.parameters['workflow-array-param']))}}"
                - name: last-param
                  value: "{{=last(fromJSON(workflow.parameters['workflow-array-param']))}}"
                - name: flatten-param
                  value: "{{=flatten(fromJSON(workflow.parameters['workflow-nested-param']))}}"
                - name: reverse-param
                  value: "{{=reverse(fromJSON(workflow.parameters['workflow-array-param']))}}"
                - name: sort-param
                  value: "{{=sort(fromJSON(workflow.parameters['workflow-array-param']))}}"
                - name: uniq-param
                  value: "{{=uniq(fromJSON(workflow.parameters['workflow-array-param']))}}"
                - name: join-param
                  value: "{{=join(fromJSON(workflow.parameters['workflow-array-param']), ', ')}}"
                - name: concat-param
                  value: "{{=concat(fromJSON(workflow.parameters['workflow-array-param']), fromJSON(workflow.parameters['workflow-array2-param']))}}"
                - name: mean-param
                  value: "{{=mean(fromJSON(workflow.parameters['workflow-array-param']))}}"
                - name: median-param
                  value: "{{=median(fromJSON(workflow.parameters['workflow-array-param']))}}"
                - name: take-param
                  value: "{{=take(fromJSON(workflow.parameters['workflow-array-param']), 2)}}"
                - name: all-param
                  value: "{{=all(fromJSON(workflow.parameters['workflow-array-param']), {# > 0})}}"
                - name: any-param
                  value: "{{=any(fromJSON(workflow.parameters['workflow-array-param']), {# > 2})}}"
                - name: one-param
                  value: "{{=one(fromJSON(workflow.parameters['workflow-array-param']), {# == 3})}}"
                - name: none-param
                  value: "{{=none(fromJSON(workflow.parameters['workflow-array-param']), {# < 0})}}"
                - name: map-param
                  value: "{{=map(fromJSON(workflow.parameters['workflow-array-param']), {# * 2})}}"
                - name: filter-param
                  value: "{{=filter(fromJSON(workflow.parameters['workflow-array-param']), {# > 1})}}"
                - name: find-param
                  value: "{{=find(fromJSON(workflow.parameters['workflow-array-param']), {# > 1})}}"
                - name: find-index-param
                  value: "{{=findIndex(fromJSON(workflow.parameters['workflow-array-param']), {# > 1})}}"
                - name: find-last-param
                  value: "{{=findLast(fromJSON(workflow.parameters['workflow-array-param']), {# > 1})}}"
                - name: find-last-index-param
                  value: "{{=findLastIndex(fromJSON(workflow.parameters['workflow-array-param']), {# > 1})}}"
                - name: group-by-param
                  value: "{{=groupBy(fromJSON(workflow.parameters['workflow-array-param']), {# % 2})}}"
                - name: count-param
                  value: "{{=count(fromJSON(workflow.parameters['workflow-array-param']), {# > 1})}}"
                - name: reduce-param
                  value: "{{=reduce(fromJSON(workflow.parameters['workflow-array-param']), {#acc + #}, 0)}}"
                - name: sum-param
                  value: "{{=sum(fromJSON(workflow.parameters['workflow-array-param']))}}"
                - name: sort-by-param
                  value: "{{=sortBy(fromJSON(workflow.parameters['workflow-array-param']))}}"
            name: array-task
            template: array
      name: entrypoint
