apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    workflows.argoproj.io/description: |
      This is an example of the ways membership expressions can be used.
  generateName: membership-
  labels:
    workflows.argoproj.io/archive-strategy: 'false'
spec:
  arguments:
    parameters:
      - name: workflow-json-param
        value: '{"isTrue":"true"}'
      - name: workflow-array-param
        value: '{"count":["one", "two", "three"]}'
      - name: bad-key-param
        value: 'badKey'
  entrypoint: entrypoint
  templates:
    - dag:
        tasks:
          - arguments:
              parameters:
                - name: in-param
                  value: "{{=workflow.parameters['bad-key-param'] in jsonpath(workflow.parameters['workflow-json-param'], '$')}}"
                - name: dot-param
                  value: "{{=jsonpath(workflow.parameters['workflow-json-param'], '$').isTrue}}"
                - name: bracket-param
                  value: "{{=jsonpath(workflow.parameters['workflow-json-param'], '$')[\"isTrue\"]}}"
                - name: array-bracket-param
                  value: "{{=jsonpath(workflow.parameters['workflow-array-param'], '$.count')[0]}}"
                # You cannot use ?. in argo workflows. if you do the parameter return the expression IE: {{=jsonpath(workflow.parameters['workflow-json-param'], '$')?.nonExistentKey}}
                # - name: optional-chaining-param
                #   value: "{{=jsonpath(workflow.parameters['workflow-json-param'], '$')?.nonExistentKey}}"
            name: membership-task
            template: membership
      name: entrypoint
    - inputs:
        parameters:
          - name: in-param
          - name: dot-param
          - name: bracket-param
          - name: array-bracket-param
      name: membership
      script:
        command:
          - '/bin/sh'
          - '-e'
        image: busybox
        source:  >
          if [ "{{inputs.parameters.in-param}}" != false ]; then exit 12; fi
                               if [ "{{inputs.parameters.dot-param}}" != true ]; then exit 13; fi
                               if [ "{{inputs.parameters.bracket-param}}" != true ]; then exit 14; fi
                               if [ "{{inputs.parameters.array-bracket-param}}" != "one" ]; then exit 15; fi
