name: release
on:
  workflow_dispatch:

permissions:
  contents: read # for checkout

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: latest
      - name: install dependencies
        run: npm clean-install
      - name: verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: build project
        run: npm run build
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release@25.0.3
